name: Build LaTeX document
on:
  push:
    branches:
      - main

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: code-of-conduct.tex

      - name: Upload built PDF
        uses: actions/upload-artifact@v3
        with:
          name: code-of-conduct
          path: code-of-conduct.pdf

  deploy-pdf:
    runs-on: ubuntu-latest
    needs:
      - build-latex
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: code-of-conduct

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy
        run: |
          git clone git@github.com:Coderdojo-Schoeneweide/website-hugo.git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cd website-hugo/
          cp ../code-of-conduct.pdf static/docs/code-of-conduct.pdf
          git add static/docs
          git commit -m "Updated Code of Conduct PDF"
          git push origin master
